### PR TITLE
Jimmyphong patch 1

### PR DESCRIPTION
**Pull request by jimmyphong**

### CODE REVIEW

**Comment by lukaspijak** [comment]
Why you need this change? Maybe it will be better this:

``` php
/** @var BulkGate\Sms\Message $message */
$message->getText()->getVariables();
```

What do you think?

**Comment by jimmyphong** [comment]
The function getVariables() did not exist in BulkGate\Sms\Message now !

**Comment by jimmyphong** [comment]
Also in Bulk Message response add getCredit() to return credit of message ! 

Thanks you !

**Comment by lukaspijak** [comment]
Features added

- getCredit() https://github.com/BulkGate/sms/commit/0091d08a5060f2502afe10a817862cb7aaa33da5
- getVariables() https://github.com/BulkGate/sms/commit/009f9876e616a8e82c774ad448a40e439a8e25cf

On variables feature you must use on BulkGate\Sms\Message\Text::text($message, $variables, true) third parameter set to true.

**Pull request closed without merging**
